### ISSUE TITLE
Research on how communication with OR is done

### ISSUE THREAD

**Issue by JVerbruggen** [OR-WindPredicition/WindPredictionAPI#15]
It is possible to get information from OpenRemote using MQTT, WS and HTTP. 

- What endpoints would interest us? 
- How do we connect with these endpoints?
- Which protocol should we use?

**Comment by JVerbruggen** [comment]
OR Developer dashboard / documentation: https://openremote.io/developers/

**Comment by Niekvandam** [comment]
See #21 for more information about the ways of communication.
