### ISSUE TITLE
OR Wind Turbine supplied data consideration

### ISSUE THREAD

**Issue by JVerbruggen** [OR-WindPredicition/WindPredictionAPI#19]
We don't know if OR Windturbines supply data on 1. wind speed or 2. power. This inflicts on our project severely, that we would in one case only have one ML model, and in the other two.

1. Windturbines supply power data

If wind turbines supply data on power, we should get predicted power data based on some forecast parameters. This model is trained by comparing the predicted power and the measured power.

Input | Output
--- | ---
Temperature | Wind power generated
Humidity | 
Air pressure | 
Wind speed | 
Wind degrees | 
Weather ID |

2. Windturbines supply wind speed data

Input | Output
--- | ---
Temperature | Wind speed
Humidity | 
Air pressure | 
Wind speed | 
Wind degrees | 
Weather ID |

Compare predicted windspeed with measured wind speed.

Input | Output
--- | ---
Wind speed | Power

An unknown function of Windspeed gives us the power. A machine learning model can find this relation for us. A rough estimate for the relationship has already been given to us:

<img src="https://user-images.githubusercontent.com/24968079/109186550-52ea9280-7791-11eb-90a1-269d7536f960.png" width="30%" />

**Comment by JVerbruggen** [comment]
Figure out what data wind turbines give us

**Comment by Niekvandam** [comment]
The wind turbine only supplies us with the currently generated power. This leaves us with method 1 as the feasible option to continue the development.
