### ISSUE TITLE
Sprint setup

### ISSUE THREAD

**Issue by JVerbruggen** [OR-WindPredicition/WindPredictionAPI#22]
We should setup sprints.

**Comment by JVerbruggen** [comment]
Once in three weeks

**Comment by JVerbruggen** [comment]
Sprint delivery on a Thursday around 15.00

**Comment by JVerbruggen** [comment]
Propose this to stakeholders!

**Comment by Niekvandam** [comment]
Proposed to stakeholders, the time for a sprint will be 3 weeks per sprint. Besides this, we are going to have Pierre Kil at every delivery who - regarding of the subject - can bring some of his colleagues.
