### ISSUE TITLE
Create C4 design for the prediction model

### ISSUE THREAD

**Issue by Niekvandam** [OR-WindPredicition/WindPredictionAPI#25]
We are unable to work on the model itself yet, but we can start on the designs of the prediction models already.

**Comment by JVerbruggen** [comment]
Flow chart also ok?

![Flow of training model-Pagina-2](https://user-images.githubusercontent.com/24968079/111807721-8d000d80-88d3-11eb-8b1e-00274316503f.png)

**Comment by Niekvandam** [comment]
![Component Diagram](https://user-images.githubusercontent.com/24568700/114037493-563d6780-9881-11eb-830c-95aa45a867b2.jpg)
![Container Diagram](https://user-images.githubusercontent.com/24568700/114037500-576e9480-9881-11eb-9685-fe096769cadf.jpg)
![System Context](https://user-images.githubusercontent.com/24568700/114037503-58072b00-9881-11eb-97b4-9ff20f92df5e.jpg)
