### ISSUE TITLE
Importing old documentation into wiki's

### ISSUE THREAD

**Issue by JVerbruggen** [OR-WindPredicition/WindPredictionAPI#3]

**Comment by JVerbruggen** [comment]
![udJSeqO](https://user-images.githubusercontent.com/24968079/109139981-69c2c200-775c-11eb-8133-a6c63c790ccc.png)

**Comment by Niekvandam** [comment]
![diagram](https://user-images.githubusercontent.com/24568700/109140448-e5247380-775c-11eb-8987-cdd53c788569.png)
