### ISSUE TITLE
Usage of machine learning in java app

### ISSUE THREAD

**Issue by JVerbruggen** [OR-WindPredicition/WindPredictionAPI#7]
I am doubting the fact that we should be using the machine learning model inside the java application.

Currently we haven't defined a project structure yet, but when we will be defining it, we should consider the fact that maybe it is not a good idea to let a Java API do machine learning calculations, especially if it is locally run on some potential raspberry pi.

Would it be better to make a web service available for our java API to call to? This web service would be hosted with a service like Amazon, where we can guarantee (video-)processing capacity. Then, we add a REST interface for our java app to let it push information that should be processed on the server.

Effectively, when the REST api is not called, the hosted web service could be training its model. Then, when an API call is done, it takes data that was supplied by the java API, processes it, and returns the result (maybe within the same API call, maybe we will need some async stuff).

What do you think? @Niekvandam @elmiratjee

**Comment by Niekvandam** [comment]
I think a solution like this would result in a way cleaner project structure and could possibly help us in our development too! We should ask OpenRemote to see what the provided hardware is to run this project on.
